#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : My Jupyter Book
author                      : The Jupyter Book community,
copyright                   : 2020,
logo                        : ""
exclude_files               : []
execute_notebooks           : auto

#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""
  sidebar_footer_text       : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'
  google_analytics_id       : "" 


#######################################################################################
# Interact link settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)

repository:
  url                       : https://github.com/ExecutableBookProject/cli  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.

thebelab:  
  use_cell_buttons          : false
  use_page_button           : false
  thebelab_button_text      : "Thebelab"  # The text to display inside the Thebelab initialization button
  codemirror_theme          : "abcdef"  # Theme for codemirror cells, for options see https://codemirror.net/doc/manual.html#config
