version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user .[testing]
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      # Run the docs so they are up-to-date
      - run:
          name: Running tests
          command: pytest

workflows:
  version: 2
  default:
    jobs:
      - tests
