version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # Get our data and merge with upstream
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user .[sphinx,circleci]
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      # Run the docs so they are up-to-date
      - run:
          name: Running notebooks in docs so they are up to date
          command: python .circleci/run_notebooks.py

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            jupyter-book build docs

      - store_artifacts:
          path: docs/_build/html/
          destination: html

      # Deploy to docs if we're on master
      - add_ssh_keys:
          fingerprints:
            - "53:80:a8:f7:12:c7:c6:72:ed:42:b0:f8:53:7d:27:1c"

      - run:
          name: Deploying to gh-pages from master branch
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]
            then
              pip install ghp-import
              ghp-import -n -p -f docs/_build/html
            fi

workflows:
  version: 2
  default:
    jobs:
      - build_docs
